name: 'nix-remarkable'
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      with:
        name: nix-remarkable
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build --arg release true -f . rmPkgs.linuxPackages.mxc_epdc_fb_damage
    - name: "Copy linuxPackages.mxc_epdc_fb_damage"
      run: "mkdir mxc_epdc_fb_damage && cp -r result/* mxc_epdc_fb_damage && chmod +w -R mxc_epdc_fb_damage"
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: mxc_epdc_fb_damage
        path: mxc_epdc_fb_damage
    - run: nix build --arg release true -f . rmPkgs.rM-vnc-server
    - name: "Copy rmPkgs.rM-vnc-server"
      run: "mkdir rM-vnc-server && cp -r result/* rM-vnc-server && chmod +w -R rM-vnc-server"
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: rM-vnc-server
        path: rM-vnc-server
    - run: nix build --arg release true -f . hostPkgs.gst-libvncclient-rfbsrc
    - name: "Copy hostPkgs.gst-libvncclient-rfbsrc"
      run: "mkdir gst-libvncclient-rfbsrc && cp -r result/* gst-libvncclient-rfbsrc && chmod +w -R gst-libvncclient-rfbsrc"
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: gst-libvncclient-rfbsrc
        path: gst-libvncclient-rfbsrc
    - run: nix build --arg release true -f . rmPkgs.remarkable_news
    - name: "Copy rmPkgs.remarkable_news"
      run: "mkdir remarkable_news && cp -r result/* remarkable_news && chmod +w -R remarkable_news"
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: remarkable_news
        path: remarkable_news
    - run: nix build --arg release true -f . rmPkgs.oxide
    - name: "Copy oxide"
      run: "mkdir oxide && cp -r result/* oxide && chmod +w -R oxide"
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: oxide
        path: oxide
